<a href="https://colab.research.google.com/github/manisharan-deep/Generative_AI_2303A52148/blob/main/G_AI_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install --upgrade scikit-learn

# Library-based computation
from sklearn.metrics import mean_absolute_error, mean_squared_error

mae_lib = mean_absolute_error(y_actual, y_pred)
mse_lib = mean_squared_error(y_actual, y_pred)
# Calculate RMSE using numpy to maintain compatibility
import numpy as np
rmse_lib = np.sqrt(mse_lib)

print(f"Library Metrics - MAE: {mae_lib}, MSE: {mse_lib}, RMSE: {rmse_lib}")

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.5/13.5 MB 90.5 MB/s eta 0:00:00
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.6.0
    Uninstalling scikit-learn-1.6.0:
      Successfully uninstalled scikit-learn-1.6.0
Library Metrics - MAE: 0.4600000000000016, MSE: 0.24600000000000147, RMSE: 0.49598387070549127


In [3]:
# Table 2: Multiclass classification metrics
y_actual = [0, 0, 1, 1, 2, 0, 0, 1, 2, 2, 0, 2, 1, 0, 2, 2]
y_pred = [0, 1, 1, 0, 2, 0, 1, 2, 2, 2, 1, 0, 2, 2, 2, 2]

# Custom implementation of confusion matrix
def confusion_matrix_multiclass(y_actual, y_pred, classes):
    matrix = [[0] * classes for _ in range(classes)]
    for a, p in zip(y_actual, y_pred):
        matrix[a][p] += 1
    return matrix

# Custom metrics
def calculate_metrics(conf_matrix):
    classes = len(conf_matrix)
    accuracy = sum(conf_matrix[i][i] for i in range(classes)) / sum(sum(row) for row in conf_matrix)
    return accuracy

classes = len(set(y_actual))
conf_matrix = confusion_matrix_multiclass(y_actual, y_pred, classes)
accuracy = calculate_metrics(conf_matrix)

print("Custom Confusion Matrix:")
for row in conf_matrix:
    print(row)
print(f"Custom Accuracy: {accuracy}")

# Library-based computation
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

conf_matrix_lib = confusion_matrix(y_actual, y_pred)
accuracy_lib = accuracy_score(y_actual, y_pred)
report_lib = classification_report(y_actual, y_pred)

print("\nLibrary Confusion Matrix:")
print(conf_matrix_lib)
print(f"Library Accuracy: {accuracy_lib}")
print("Classification Report:")
print(report_lib)


Custom Confusion Matrix:
[2, 3, 1]
[1, 1, 2]
[1, 0, 5]
Custom Accuracy: 0.5

Library Confusion Matrix:
[[2 3 1]
 [1 1 2]
 [1 0 5]]
Library Accuracy: 0.5
Classification Report:
              precision    recall  f1-score   support

           0       0.50      0.33      0.40         6
           1       0.25      0.25      0.25         4
           2       0.62      0.83      0.71         6

    accuracy                           0.50        16
   macro avg       0.46      0.47      0.45        16
weighted avg       0.48      0.50      0.48        16

